/**
 * Maze Adventure — 16 hand-tuned levels across four tiers.
 *
 * The maze itself is generated by randomised depth-first search, which always
 * yields a "perfect" maze: exactly one path between any two cells, so a level
 * is never unsolvable. Difficulty grows three ways:
 *   • size        — 6×6 up to 16×16
 *   • stars       — optional pick-ups that force detours off the direct route
 *   • keys/doors  — from the Hard tier, a locked door blocks the exit until
 *                   the key is collected, so the route becomes a two-leg trip
 *
 * Controls are deliberately redundant: swipe anywhere on the maze, tap an
 * adjacent square, use the big arrow pad, or arrow keys on a keyboard.
 * Progress (unlocked level + best step count) is saved to the child's profile.
 */
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Lock, RotateCcw, Trophy, ChevronRight, Star } from "lucide-react";
import { Shell, Btn, Confetti, toast } from "../../components/UI";
import { sfx, speak, haptic } from "../../lib/audio";
import { useStore } from "../../lib/store";

interface Cell { walls: [boolean, boolean, boolean, boolean]; seen: boolean } // N,E,S,W

export interface MazeLevel {
  n: number;        // grid size
  stars: number;    // collectibles to gather before the exit opens
  keys: number;     // locked doors (0 or 1)
  tier: "Easy" | "Medium" | "Hard" | "Expert";
  name: string;
}

/** 16 levels: four per tier, each a clear step up from the last. */
export const LEVELS: MazeLevel[] = [
  { n: 6, stars: 0, keys: 0, tier: "Easy", name: "First Steps" },
  { n: 6, stars: 1, keys: 0, tier: "Easy", name: "One Star" },
  { n: 7, stars: 1, keys: 0, tier: "Easy", name: "Garden Path" },
  { n: 7, stars: 2, keys: 0, tier: "Easy", name: "Two Treasures" },

  { n: 8, stars: 2, keys: 0, tier: "Medium", name: "Winding Woods" },
  { n: 9, stars: 2, keys: 0, tier: "Medium", name: "Twisty Trail" },
  { n: 10, stars: 3, keys: 0, tier: "Medium", name: "Star Hunt" },
  { n: 10, stars: 3, keys: 0, tier: "Medium", name: "Long Way Round" },

  { n: 11, stars: 3, keys: 1, tier: "Hard", name: "The Locked Gate" },
  { n: 12, stars: 3, keys: 1, tier: "Hard", name: "Key Quest" },
  { n: 12, stars: 4, keys: 1, tier: "Hard", name: "Deep Tunnels" },
  { n: 13, stars: 4, keys: 1, tier: "Hard", name: "The Long Maze" },

  { n: 14, stars: 4, keys: 1, tier: "Expert", name: "Labyrinth" },
  { n: 14, stars: 5, keys: 1, tier: "Expert", name: "Lost Caverns" },
  { n: 15, stars: 5, keys: 1, tier: "Expert", name: "The Great Maze" },
  { n: 16, stars: 6, keys: 1, tier: "Expert", name: "Champion's Run" }
];

const TIER_STYLE: Record<MazeLevel["tier"], string> = {
  Easy: "from-mint/20 to-mint/5",
  Medium: "from-sky/20 to-sky/5",
  Hard: "from-sun/25 to-sun/5",
  Expert: "from-coral/25 to-coral/5"
};

function generate(size: number): Cell[] {
  const cells: Cell[] = Array.from({ length: size * size }, () => ({
    walls: [true, true, true, true], seen: false
  }));
  const at = (x: number, y: number) => cells[y * size + x];
  const stack: [number, number][] = [[0, 0]];
  at(0, 0).seen = true;
  const DIRS: [number, number, number, number][] = [[0, -1, 0, 2], [1, 0, 1, 3], [0, 1, 2, 0], [-1, 0, 3, 1]];
  while (stack.length) {
    const [x, y] = stack[stack.length - 1];
    const opts = DIRS.filter(([dx, dy]) => {
      const nx = x + dx, ny = y + dy;
      return nx >= 0 && ny >= 0 && nx < size && ny < size && !at(nx, ny).seen;
    });
    if (!opts.length) { stack.pop(); continue; }
    const [dx, dy, w, opp] = opts[Math.floor(Math.random() * opts.length)];
    const nx = x + dx, ny = y + dy;
    at(x, y).walls[w] = false;
    at(nx, ny).walls[opp] = false;
    at(nx, ny).seen = true;
    stack.push([nx, ny]);
  }
  return cells;
}

/** Breadth-first distances from the start — used to place things far away. */
function distances(cells: Cell[], size: number): number[] {
  const dist = Array(size * size).fill(-1);
  dist[0] = 0;
  const q = [0];
  const DIRS: [number, number, number][] = [[0, -1, 0], [1, 0, 1], [0, 1, 2], [-1, 0, 3]];
  while (q.length) {
    const i = q.shift()!;
    const x = i % size, y = Math.floor(i / size);
    for (const [dx, dy, w] of DIRS) {
      if (cells[i].walls[w]) continue;
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= size || ny >= size) continue;
      const ni = ny * size + nx;
      if (dist[ni] === -1) { dist[ni] = dist[i] + 1; q.push(ni); }
    }
  }
  return dist;
}

/* ---------------- Level list ---------------- */

export default function MazeAdventure({ onBack }: { onBack: () => void }) {
  const { profile } = useStore();
  const [playing, setPlaying] = useState<number | null>(null);
  const unlocked = profile?.mazeLevel ?? 1;

  if (playing !== null) {
    return <MazeGame levelIndex={playing} onBack={() => setPlaying(null)}
      onNext={() => setPlaying(i => (i !== null && i + 1 < LEVELS.length ? i + 1 : null))} />;
  }

  return (
    <Shell title="Maze Adventure 🌀" subtitle="16 levels — from first steps to champion" onBack={onBack} wide>
      {(["Easy", "Medium", "Hard", "Expert"] as const).map(tier => (
        <div key={tier} className="mb-6">
          <h2 className="mb-2 text-lg font-bold">
            {tier === "Easy" ? "🟢" : tier === "Medium" ? "🔵" : tier === "Hard" ? "🟠" : "🔴"} {tier}
          </h2>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {LEVELS.map((lv, i) => lv.tier === tier && (
              <button
                key={i}
                onClick={() => {
                  if (i + 1 > unlocked) { toast("Finish the level before this one first 🔒"); return; }
                  sfx.tap(); setPlaying(i);
                }}
                aria-label={`Level ${i + 1}: ${lv.name}${i + 1 > unlocked ? ". Locked" : ""}`}
                className={`glass flex min-h-28 flex-col items-center justify-center gap-1 rounded-[1.5rem] bg-gradient-to-br p-4
                  ${TIER_STYLE[tier]} ${i + 1 > unlocked ? "opacity-50" : ""}`}
              >
                {i + 1 > unlocked
                  ? <Lock size={22} className="text-ink-2" aria-hidden />
                  : <span className="text-xl font-extrabold text-tint">{i + 1}</span>}
                <span className="text-center text-sm font-bold leading-tight">{lv.name}</span>
                <span className="text-xs text-ink-2">
                  {lv.n}×{lv.n}{lv.stars ? ` · ${lv.stars}⭐` : ""}{lv.keys ? " · 🔑" : ""}
                </span>
                {profile?.mazeBest?.[i] !== undefined && (
                  <span className="text-xs font-bold text-mint">best {profile.mazeBest[i]}</span>
                )}
              </button>
            ))}
          </div>
        </div>
      ))}
    </Shell>
  );
}

/* ---------------- One playable level ---------------- */

function MazeGame({ levelIndex, onBack, onNext }: {
  levelIndex: number; onBack: () => void; onNext: () => void;
}) {
  const { dispatch, profile } = useStore();
  const lv = LEVELS[levelIndex];
  const [attempt, setAttempt] = useState(0);

  const { cells, starsAt, keyAt, doorAt, exitAt } = useMemo(() => {
    const size = lv.n;
    const cells = generate(size);
    const dist = distances(cells, size);
    const exitAt = size * size - 1;

    // Place the key/door so the door sits on the ONLY path to the exit: we put
    // the door on the exit cell itself and the key somewhere far from start.
    const order = dist.map((d, i) => [d, i] as const).sort((a, b) => b[0] - a[0]);
    const far = order.filter(([, i]) => i !== 0 && i !== exitAt).map(([, i]) => i);

    const keyAt = lv.keys ? far[Math.floor(far.length * 0.25)] : -1;
    const doorAt = lv.keys ? exitAt : -1;

    // Stars go to dead-ends spread through the maze, forcing detours.
    const deadEnds = cells
      .map((c, i) => [c.walls.filter(Boolean).length, i] as const)
      .filter(([w, i]) => w === 3 && i !== 0 && i !== exitAt && i !== keyAt)
      .map(([, i]) => i);
    const pool = deadEnds.length >= lv.stars ? deadEnds : far;
    const starsAt = pool.sort(() => Math.random() - 0.5).slice(0, lv.stars);

    return { cells, starsAt, keyAt, doorAt, exitAt };
  }, [lv, attempt]);

  const [pos, setPos] = useState(0);
  const [got, setGot] = useState<Set<number>>(new Set());
  const [hasKey, setHasKey] = useState(false);
  const [steps, setSteps] = useState(0);
  const [won, setWon] = useState(false);
  const size = lv.n;

  useEffect(() => { setPos(0); setGot(new Set()); setHasKey(false); setSteps(0); setWon(false); }, [attempt, levelIndex]);

  const starsLeft = lv.stars - got.size;
  const best = profile?.mazeBest?.[levelIndex];

  const move = useCallback((dx: number, dy: number) => {
    if (won) return;
    setPos(prev => {
      const x = prev % size, y = Math.floor(prev / size);
      const wall = dy === -1 ? 0 : dx === 1 ? 1 : dy === 1 ? 2 : 3;
      if (cells[prev].walls[wall]) { sfx.tap(); return prev; }   // bumped a wall
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= size || ny >= size) return prev;
      const ni = ny * size + nx;

      // Locked door: need the key first.
      if (ni === doorAt && lv.keys && !hasKey) {
        sfx.wrong();
        toast("The gate is locked — find the 🔑 first!");
        return prev;
      }
      // Exit needs all stars.
      if (ni === exitAt && starsLeft > 0) {
        sfx.wrong();
        toast(`Collect ${starsLeft} more ⭐ before you leave!`);
        return prev;
      }

      sfx.pop(); haptic(5);
      setSteps(s => s + 1);

      if (starsAt.includes(ni) && !got.has(ni)) {
        sfx.chime();
        setGot(g => new Set(g).add(ni));
      }
      if (ni === keyAt && !hasKey) {
        sfx.chime();
        setHasKey(true);
        speak("You found the key!");
      }
      if (ni === exitAt) {
        sfx.win(); haptic(30);
        setWon(true);
      }
      return ni;
    });
  }, [cells, size, doorAt, exitAt, hasKey, keyAt, starsAt, got, starsLeft, lv.keys, won]);

  // Award once, when the level is first won.
  const awarded = useRef(false);
  useEffect(() => { awarded.current = false; }, [attempt, levelIndex]);
  useEffect(() => {
    if (!won || awarded.current) return;
    awarded.current = true;
    dispatch({ type: "mazeCleared", levelIndex, steps });
    dispatch({ type: "award", stars: lv.tier === "Easy" ? 1 : lv.tier === "Medium" ? 2 : 3, activity: `maze-${lv.tier.toLowerCase()}` });
    speak(`Level complete in ${steps} steps!`);
  }, [won, steps, levelIndex, dispatch, lv.tier]);

  /* Keyboard */
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const m: Record<string, [number, number]> = {
        ArrowUp: [0, -1], ArrowDown: [0, 1], ArrowLeft: [-1, 0], ArrowRight: [1, 0]
      };
      if (m[e.key]) { e.preventDefault(); move(...m[e.key]); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [move]);

  /* Swipe: the natural gesture on a phone or tablet. */
  const touch = useRef<[number, number] | null>(null);
  function onPointerDown(e: React.PointerEvent) { touch.current = [e.clientX, e.clientY]; }
  function onPointerUp(e: React.PointerEvent) {
    if (!touch.current) return;
    const [sx, sy] = touch.current;
    touch.current = null;
    const dx = e.clientX - sx, dy = e.clientY - sy;
    if (Math.abs(dx) < 24 && Math.abs(dy) < 24) return;   // a tap, not a swipe
    if (Math.abs(dx) > Math.abs(dy)) move(dx > 0 ? 1 : -1, 0);
    else move(0, dy > 0 ? 1 : -1);
  }

  return (
    <Shell
      title={`Level ${levelIndex + 1} — ${lv.name}`}
      subtitle={won ? `🎉 Finished in ${steps} steps!` : "Swipe, tap a square next to you, or use the arrows"}
      onBack={onBack}
      wide
    >
      {won && <Confetti />}

      {/* Status strip */}
      <div className="mb-3 flex flex-wrap items-center justify-center gap-2 text-sm font-bold">
        <span className="glass rounded-full px-4 py-2">{lv.tier}</span>
        <span className="glass rounded-full px-4 py-2">👣 {steps}</span>
        {lv.stars > 0 && (
          <span className="glass rounded-full px-4 py-2">
            ⭐ {got.size}/{lv.stars}
          </span>
        )}
        {lv.keys > 0 && (
          <span className={`rounded-full px-4 py-2 ${hasKey ? "bg-sun text-ink" : "glass"}`}>
            {hasKey ? "🔑 got it" : "🔒 locked"}
          </span>
        )}
        {best !== undefined && <span className="glass rounded-full px-4 py-2 text-mint">🏆 best {best}</span>}
      </div>

      <div className="glass mx-auto max-w-2xl rounded-[1.75rem] p-3"
        onPointerDown={onPointerDown} onPointerUp={onPointerUp}
        style={{ touchAction: "none" }}>
        <div className="grid" style={{ gridTemplateColumns: `repeat(${size}, 1fr)` }}
          role="application" aria-label={`Maze level ${levelIndex + 1}, ${size} by ${size}. ${steps} steps taken.`}>
          {cells.map((c, i) => {
            const x = i % size, y = Math.floor(i / size);
            const isPlayer = pos === i;
            const isExit = i === exitAt;
            const isStar = starsAt.includes(i) && !got.has(i);
            const isKey = i === keyAt && !hasKey;
            const adjacent = Math.abs((pos % size) - x) + Math.abs(Math.floor(pos / size) - y) === 1;
            // Wall thickness scales down as mazes get big, so they stay readable.
            const w = size > 12 ? 2 : 3;
            return (
              <button
                key={i}
                onClick={() => adjacent && move(x - (pos % size), y - Math.floor(pos / size))}
                aria-label={
                  isPlayer ? "You are here"
                    : isExit ? "The exit"
                    : isStar ? "A star to collect"
                    : isKey ? "A key"
                    : adjacent ? "Move here" : "Maze path"
                }
                className="grid aspect-square place-items-center bg-white/70"
                style={{
                  fontSize: size > 12 ? "0.7rem" : size > 9 ? "0.9rem" : "1.2rem",
                  borderTop: `${w}px solid ${c.walls[0] ? "#6e6e87" : "transparent"}`,
                  borderRight: `${w}px solid ${c.walls[1] ? "#6e6e87" : "transparent"}`,
                  borderBottom: `${w}px solid ${c.walls[2] ? "#6e6e87" : "transparent"}`,
                  borderLeft: `${w}px solid ${c.walls[3] ? "#6e6e87" : "transparent"}`,
                  background: isExit ? (starsLeft > 0 || (lv.keys > 0 && !hasKey) ? "#ffe6e6" : "#d9f7e8") : undefined
                }}
              >
                {isPlayer ? <motion.span layoutId="hero" aria-hidden>🙂</motion.span>
                  : isStar ? <span aria-hidden>⭐</span>
                  : isKey ? <span aria-hidden>🔑</span>
                  : isExit ? <span aria-hidden>{starsLeft > 0 || (lv.keys > 0 && !hasKey) ? "🔒" : "🏁"}</span>
                  : adjacent ? <span aria-hidden className="h-1.5 w-1.5 rounded-full bg-tint/25" />
                  : null}
              </button>
            );
          })}
        </div>
      </div>

      {/* Arrow pad */}
      <div className="mt-5 flex flex-col items-center gap-2">
        <Btn kind="soft" ariaLabel="Move up" onClick={() => move(0, -1)} className="!px-8">▲</Btn>
        <div className="flex gap-2">
          <Btn kind="soft" ariaLabel="Move left" onClick={() => move(-1, 0)} className="!px-8">◀</Btn>
          <Btn kind="soft" ariaLabel="Move down" onClick={() => move(0, 1)} className="!px-8">▼</Btn>
          <Btn kind="soft" ariaLabel="Move right" onClick={() => move(1, 0)} className="!px-8">▶</Btn>
        </div>
      </div>

      <div className="mt-5 flex flex-wrap justify-center gap-3">
        <Btn kind="soft" onClick={() => setAttempt(a => a + 1)}>
          <RotateCcw size={18} aria-hidden /> Try again
        </Btn>
        {won && levelIndex + 1 < LEVELS.length && (
          <Btn kind="good" onClick={onNext}>Next level <ChevronRight size={18} aria-hidden /></Btn>
        )}
        {won && levelIndex + 1 >= LEVELS.length && (
          <Btn kind="good" onClick={onBack}><Trophy size={18} aria-hidden /> All levels done!</Btn>
        )}
      </div>
    </Shell>
  );
}
